### ISSUE TITLE
/EH is confused with /E

### ISSUE THREAD

**Issue by mlogan** [inorton/cclash#16]
cclash seems to interpret the /EH option as /E, which is an unsupported option. It looks like the cause is at https://github.com/inorton/cclash/blob/23d8beb0e57bf4e94650ebee0abefcd1690f50b6/CClash/Compiler.cs#L298

I'd be happy to submit a pull request to fix this, but I notice there hasn't been a release in over a year, so I want to make sure this project is still maintained before I take the time to do that.

**Comment by mlogan** [comment]
Sorry, I don't know how I got this problem in the first place, but I can't reproduce it and I've verified that /EH is definitely parsed correctly.

**Comment by inorton** [comment]
no prob :)  /E dumps the pre-processor output to stdout.
