### ISSUE TITLE
Missing AssemblyInfo.cs file in cct project

### ISSUE THREAD

**Issue by friofry** [inorton/cclash#22]
Hi,
I've failed to compile cclash.sln because cct\Properties\AssemblyInfo.cs is missing:
```
2>------ Build started: Project: cct, Configuration: Release Any CPU ------
2>CSC : error CS2001: Source file 'Properties\AssemblyInfo.cs' could not be found```

**Comment by inorton** [comment]
ooh thanks, just a mo!

**Comment by inorton** [comment]
added and pushed, sorry about that! darn visual studio git plugin isn't very helpful

**Comment by friofry** [comment]
Thanks! I'll try this change )
