### ISSUE TITLE
How to see stats? How to specify folder for cache?

### ISSUE THREAD

**Issue by Jimilian** [inorton/cclash#25]
Hi! Is it possible to see stats? Something similar to `ccache -s`?
And how to specify folder for cached  files?

**Comment by Jimilian** [comment]
In source code I found CCLASH_DIR. I specified it, but get any benefits from cclash. Also I found file `$CCLASH_DIR\outputs\st\stats\unsupported.txt`. It contains 20. What does it mean? Could you help me to understand how to setup your script to see compilation time benefits in my project?

**Comment by inorton** [comment]
Hi Jimilian, Yes, sadly not everything can get much of a benefit. Specifically if you are using PDB debug files then I've not found a way to cache that properly. 

You can set some other environment variables to check why cclash wasn't able to help. If you set CCLASH_MISSES to a file path. It will then log which compiler calls failed to gain a cache hit and (hopefully why)

**Comment by TheOneRing** [comment]
Now we have another problem.

``        cl -Yuqmake_pch.h -FIqmake_pch.h -Fpqmake_pch.pch -c -Fo./ -Fdqmake.pdb  -W3 -nologo -O1  /MP /D_CRT_SECURE_NO_W
ARNINGS /D_SCL_SECURE_NO_WARNINGS /Zc:strictStrings /w44456 /w44457 /w44458 /wd4577   -Iq:\qtbase\qmake -Iq:\qtbase\qmak
e\library -Iq:\qtbase\qmake\generators -Iq:\qtbase\qmake\generators\unix -Iq:\qtbase\qmake\generators\win32 -Iq:\qtbase\
qmake\generators\mac -Iq:\qtbase\qmake\generators\integrity  -I..\include -I..\include\QtCore -I..\include\QtCore\5.7.0
-I..\include\QtCore\5.7.0\QtCore  -I..\src\corelib\global -DHAVE_QCONFIG_CPP  -Iq:\qtbase\mkspecs\win32-msvc2015   -Iq:\
qtbase\tools\shared  -DQT_VERSION_STR=\"5.7.0\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=7 -DQT_VERSION_PATCH=0  -DQT_BUI
LD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_NO_COMPONENT -DQT_NO_COMPRE
SS  -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -DQT_NO_DATASTREAM  -DQT_NO_FOREACH  -DUNICODE -DQT_CRYPTOGRAPHI
CHASH_ONLY_SHA1 -DQT_JSON_READONLY -DQT_NO_STANDARDPATHS  q:\qtbase\qmake\project.cpp q:\qtbase\qmake\main.cpp q:\qtbase
\qmake\option.cpp q:\qtbase\qmake\property.cpp q:\qtbase\qmake\meta.cpp
project.cpp
main.cpp
option.cpp
q:\qtbase\qmake\project.cpp: warning C4005: 'QT_VERSION_STR': macro redefinition
q:\qtbase\qmake\project.cpp: note: command-line arguments:  see previous definition of 'QT_VERSION_STR'
q:\qtbase\qmake\project.cpp: warning C4651: '/DQT_VERSION_STR=5.7.0-DQT_VERSION_MAJOR=5' specified for precompiled heade
r but not for current compile
q:\qtbase\qmake\main.cpp: warning C4005: 'QT_VERSION_STR': macro redefinition
q:\qtbase\qmake\main.cpp: note: command-line arguments:  see previous definition of 'QT_VERSION_STR'
q:\qtbase\qmake\main.cpp: warning C4651: '/DQT_VERSION_STR=5.7.0-DQT_VERSION_MAJOR=5' specified for precompiled header b
ut not for current compile``

**Comment by inorton** [comment]
Not really a bug

**Comment by lp35** [comment]
Hello,

How do you specify cache dir?

Thanks,

**Comment by inorton** [comment]
Hiya, you can change where the cache is stored by setting the CCLASH_DIR environment variable to a path you wish to use
