### ISSUE TITLE
Escaping of \"FOOO\" is broken.

### ISSUE THREAD

**Issue by TheOneRing** [inorton/cclash#26]
Escaping of \"FOOO\" is broken. 

`       cl -c -nologo -Zc:wchar_t -W3 -GR -EHsc -w34100 -w34189 -wd4577   -DUNICODE -DQT_NO_CODECS -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_LITE_COMPONENT -DQT_NO_COMPRESS -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -D_CRT_SECURE_NO_DEPRECATE -DQT_BOOTSTRAPPED -DQT_BUILD_CONFIGURE -DQT_USE_QSTRINGBUILDER -DQT_VERSION_STR=\"5.7.0\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=7 -DQT_VERSION_PATCH=0 -I"..\..\include" -I"..\..\include\QtCore" -I"..\..\include\QtCore\5.7.0" -I"..\..\include\QtCore\5.7.0\QtCore" -I"q:\qtbase\tools\shared" -I"q:\qtbase\mkspecs\win32-msvc2012" q:\qtbase\src\corelib\io\qfile.cpp q:\qtbase\src\corelib\io\qfileinfo.cpp q:\qtbase\src\corelib\io\qabstractfileengine.cpp q:\qtbase\src\corelib\io\qfilesystementry.cpp q:\qtbase\src\corelib\io\qfilesystemengine.cpp                                         qglobal.cpp                                                                                                             q:\qtbase\src\corelib\global\qglobal.cpp(1024): error C2143: syntax error: missing ';' before 'constant'                q:\qtbase\src\corelib\global\qglobal.cpp(1024): error C2440: 'return': cannot convert from 'double' to 'const char *'   jom: R:\build\libs\qtbase\work\msvc2015-Debug-5.7\tools\configure\Makefile [qglobal.obj] Error 2                                cl -c -nologo -Zc:wchar_t -W3 -GR -EHsc -w34100 -w34189 -wd4577   -DUNICODE -DQT_NO_CODECS -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_LITE_COMPONENT -DQT_NO_COMPRESS -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -D_CRT_SECURE_NO_DEPRECATE -DQT_BOOTSTRAPPED -DQT_BUILD_CONFIGURE -DQT_USE_QSTRINGBUILDER -DQT_VERSION_STR=\"5.7.0\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=7 -DQT_VERSION_PATCH=0 -I"..\..\include" -I"..\..\include\QtCore" -I"..\..\include\QtCore\5.7.0" -I"..\..\include\QtCore\5.7.0\QtCore" -I"q:\qtbase\tools\shared" -I"q:\qtbase\mkspecs\win32-msvc2012" q:\qtbase\src\corelib\io\qfilesystemengine_win.cpp q:\qtbase\src\corelib\io\qfilesystemiterator_win.cpp q:\qtbase\src\corelib\io\qfsfileengine.cpp q:\qtbase\src\corelib\io\qfsfileengine_win.cpp q:\qtbase\src\corelib\io\qfsfileengine_iterator.cpp  `

The source code at that location is

`const char *qVersion() Q_DECL_NOTHROW
{
    return QT_VERSION_STR;
}`

Using 0.3.17

**Comment by inorton** [comment]
Hiya, 

`-DQT_VERSION_STR=\"5.7.0\"`

Ok, yes, I'd look at that and expect the \" NOT to vanish when expanded.

**Comment by inorton** [comment]
I "think" I've fixed this. I'll push a commit soon

**Comment by TheOneRing** [comment]
Now we have another problem.

``        cl -Yuqmake_pch.h -FIqmake_pch.h -Fpqmake_pch.pch -c -Fo./ -Fdqmake.pdb  -W3 -nologo -O1  /MP /D_CRT_SECURE_NO_W
ARNINGS /D_SCL_SECURE_NO_WARNINGS /Zc:strictStrings /w44456 /w44457 /w44458 /wd4577   -Iq:\qtbase\qmake -Iq:\qtbase\qmak
e\library -Iq:\qtbase\qmake\generators -Iq:\qtbase\qmake\generators\unix -Iq:\qtbase\qmake\generators\win32 -Iq:\qtbase\
qmake\generators\mac -Iq:\qtbase\qmake\generators\integrity  -I..\include -I..\include\QtCore -I..\include\QtCore\5.7.0
-I..\include\QtCore\5.7.0\QtCore  -I..\src\corelib\global -DHAVE_QCONFIG_CPP  -Iq:\qtbase\mkspecs\win32-msvc2015   -Iq:\
qtbase\tools\shared  -DQT_VERSION_STR=\"5.7.0\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=7 -DQT_VERSION_PATCH=0  -DQT_BUI
LD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_NO_COMPONENT -DQT_NO_COMPRE
SS  -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -DQT_NO_DATASTREAM  -DQT_NO_FOREACH  -DUNICODE -DQT_CRYPTOGRAPHI
CHASH_ONLY_SHA1 -DQT_JSON_READONLY -DQT_NO_STANDARDPATHS  q:\qtbase\qmake\project.cpp q:\qtbase\qmake\main.cpp q:\qtbase
\qmake\option.cpp q:\qtbase\qmake\property.cpp q:\qtbase\qmake\meta.cpp
project.cpp
main.cpp
option.cpp
q:\qtbase\qmake\project.cpp: warning C4005: 'QT_VERSION_STR': macro redefinition
q:\qtbase\qmake\project.cpp: note: command-line arguments:  see previous definition of 'QT_VERSION_STR'
q:\qtbase\qmake\project.cpp: warning C4651: '/DQT_VERSION_STR=5.7.0-DQT_VERSION_MAJOR=5' specified for precompiled heade
r but not for current compile
q:\qtbase\qmake\main.cpp: warning C4005: 'QT_VERSION_STR': macro redefinition
q:\qtbase\qmake\main.cpp: note: command-line arguments:  see previous definition of 'QT_VERSION_STR'
q:\qtbase\qmake\main.cpp: warning C4651: '/DQT_VERSION_STR=5.7.0-DQT_VERSION_MAJOR=5' specified for precompiled header b
ut not for current compile``

**Comment by inorton** [comment]
Ok! hang on

**Comment by inorton** [comment]
There, try now, I'd accidentally missed out adding a space between arguments in the last commit

**Comment by TheOneRing** [comment]
Thanks

**Comment by TheOneRing** [comment]
Issue is fixed

**Comment by inorton** [comment]
Excellent!
